baseURL = "http://people-unleashed.com/"
languageCode = "en-us"
title = "People Unleashed"
theme = "story"
paginate = 5
buildFuture = true

[[menu.social]]
 

[[menu.main]]
  name = "Talks"
  title = "Talks"
  url = "/talks/"

[[menu.main]]
  name = "Slides"
  title = "Slides"
  url = "/slides/"

[[menu.main]]
  name = "Archives"
  title = "Archives"
  url = "/archives/"

[params]
  author = "Baron Schwartz"
  twitter = "xaprb"
  classes = []

[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML", "RSS"]


